### ISSUE TITLE
Direct Quotes

### ISSUE THREAD

**Issue by Hilla-Merhav** [IAHLT/UD_Hebrew#13]
@amir-zeldes
Should we tag direct quotes as `ccomp`, as we do in case of indirect quotes?
בן-גוריון כתב ביומנו ""ילדים מתים כזבובים... עלינו להציל אותם.

**Comment by amir-zeldes** [comment]
Yes!

**Comment by Hilla-Merhav** [comment]
@amir-zeldes 
Thanks! 
I have a different case of direct quotes now, not in ccomp position but kind of an nmod…

המייסדים הטובים ביותר יהיו אלה עם **סיפור** כמו ‘**עבדתי** בגוגל וראיתי שהם לא מטפלים באיזו בעיה, אז אני ועוד חבר עזבנו ואנחנו בונים משהו לפתור את זה'

How do you recommend connecting (sipur, avadti) and (avadti, kmo)?

**Comment by amir-zeldes** [comment]
You may not like this (I know I don't), but that is an oblique clause modifier (modifier clause introduced by a preposition), and UD's way of saying "oblique clause modifier" is advcl. So although it is quite jarring with the name "adverbial clause" (since it's not adverbial), the expected link is:

advcl(sipur, avadeti)
mark(avadeti, kmo)

It helps to just consider 'advcl' an arbitrary label, but it makes me shudder every time. I wish they'd called it `cobl` (I think Adam Przepiorkowski or someone wrote a paper calling for this to happen too)

**Comment by strasss** [comment]
@amir-zeldes @hilla-merhav
Sorry to reopen this closed issue, guys, but running into the following sentence 
הוא (אדנאואר) אמר לשרת: "אני מוכן לשמוע זאת, גרמניה אינה מוכנה" (Funnily enough, this time it's Moshe Sharet!)
I suddenly remembered Hilla's question about the Ben Gurion quote and Amir's answer here,
but then I also recalled that in Universal Dependencies by de Marneffe, Manning, Nivre & Zeman (2021) page 25 
--- (forgive my poor citing skills, I'm quite rusty)  ----
under "3.3.3 __Parataxis_" they mention 'reported speech' as one of the cases the parataxis relation is to be used.
 
And I think I actually used parataxis in quite a few of those early on in the geektime sentences.

Are those considered 'reported speech'?

**Comment by amir-zeldes** [comment]
I think the topic of parataxis for reported speech is controversial in UD, at least in some constructions. I think everyone agrees that 1. is `ccomp` and 2. is `parataxis`:

1. I said we should go  (ccomp(said, go))
2. "In that case," I said, "we should go" (root(go), parataxis(go, said) - basically treating 'said' as parenthetical)

The issue with quoted speech being `parataxis` in UD was apparently motivated by Germanic languages with V2 to V-final inversion in subordinate clauses, such as German or Swedish (glossed as English for convenience):

  * I said that Kim with me went (German word order, V-last subordination triggered by "that", clearly ccomp)
  * I said: "Kim went with me" (speech clause has verb-second order in German, looks less like subordination in continental Germanic)

On the strength of this evidence, a guideline was developed which was expanded to _all_ languages, even ones where no such evidence existed (e.g. English, Hebrew). I pointed out to @jnivre that this was problematic, firstly because in spoken language we can't see quotation marks, and secondly because by this logic, V2 adverbial clauses in Germanic (which are unusual, but happen nonetheless) are also `parataxis` (which no one seems to think).

I find it difficult to recommend this treatment of quoted speech in Hebrew, which has no syntactic grounds for anything but `ccomp` here. In my opinion, the main function of dependency grammar is to reflect valency: speech verbs are expected to take complement clauses, and marking this as `parataxis` looks to me like the argument structure is defective (it would mean the speech verb is intransitive, being used without an object, and then there's this coincidental quotation "arranged next to it" - the literal meaning of parataxis).

I'm not sure if @jnivre has something to add - I've put this topic on the agenda for discussion at an upcoming UD meeting as well.
