### ISSUE TITLE
Mood=Irr 

### ISSUE THREAD

**Issue by Hilla-Merhav** [IAHLT/UD_Hebrew#26]
@amir-zeldes

In irrealis structure - היה+בינוני - we assign the feature Mood=Irr to the beinoni, and we don't assign any tense feature to the beinoni.

What about the AUX – היה? Should we add Tense=Past? I am asking because semantically I think irrealis mood doesn't really refer to the past. For example, I can say – 

**לו היית אוהב אותי באמת, לא היית נוסע**

to a person that **is going to** leave the country in a week - in the future. And the love feelings are also relevant to the present. 
So maybe the היה shouldn't get any tense. What do you think?

**Comment by amir-zeldes** [comment]
I think the decision is up to us, there isn't a universal guidelines on this AFAIK. The tension is basically that semantically, it is not past tense, but morphologically, it is part of the past-tense conjugation system in Hebrew (the Afro-Asiatic suffix conjugation, 'perfect' or whatever we want to call it). 

So the options are:
  * Tag it as Past since we want to be able to easily find all verbs in the suffix conjugation form
  * Not assign Tense, since semantically it is not past

Any thoughts @yifatbm @ivrit ?

**Comment by yifatbm** [comment]
Hey, sorry for the delayed reply.. I honestly don't have any strong feelings about it, but I slightly support the 1st option, just to be consistent with the rest of our guidelines (e.g. NOUNs/ADJs are assigned with Gender accr to their morphology, and not semantics); and also to the UD focus in general, which is syntactic rather than semantic. 
@Hilla-Merhav - what's your take on this?

**Comment by Hilla-Merhav** [comment]
@yifatbm @amir-zeldes 

I sympathize with this consideration, it's just like our decision to mark Aspect=Prog on any construction of היה+בינוני (except for irrealis mood, of course) – even when it's not semantically progressive aspect – like ניתן היה, נראה היה.
May I add this decision to the Guidelines? That "היה" receives Tense=Past also in irrealis mood, even though in these cases it doesn't refer to the past?

**Comment by yifatbm** [comment]
@Hilla-Merhav @amir-zeldes
Yes, looks lie Amir is also happy with both options. so I think you can safely update the guidelines :) Thanks a lot!
