### ISSUE TITLE
The expression `הרי ש...`

### ISSUE THREAD

**Issue by Hilla-Merhav** [IAHLT/UD_Hebrew#27]
@amir-zeldes

The expression הרי ש opens a main clause, usually coming after a dependent clause – 

**מאחר ש**החוק לא אסר זאת, **הרי ש**זה חוקי
**אף ש**הוא השתתף במחקר, **הרי ש**הוא לא תרם לו דבר
**אם** בכלל קרה שם משהו, **הרי ש**זה קרה בלילה

Technically it seems the `root` govern an SCONJ through `mark`, but IMO הרי ש is no more than one adverbial unit (the "standard" form is just הרי), so I think it would be better to analyze is as a `fixed` expression (and the `root` should govern it through `advmod`). 

So if we take the first example **מאחר ש**החוק לא אסר זאת, **הרי ש**זה חוקי
Instead of `advmod`(xuki, harey)+`mark`(xuki, she), I suggest:

`advmod`(xuki, harey)
`fixed`(harey, she)

What do you think?

**Comment by amir-zeldes** [comment]
I sympathize with this, but I think it would cause some problems (never minding how it is in HTB, which is advmod). The basic problem IMO is that הרי can sometimes also be postponed like a typical adverb, and we presumably want the same analysis for:

  * הרי זה טעים
  * זה טעים הרי

In this case I think mark would be bad. If that's accepted, then the question what to do with הרי reduces to whether we want it to be a fixed SCONJ (it certainly can't be postponed, so it's not ridiculous), but then it's different from הרי alone, or do we say it's always advmod, in which case we could connect it with parataxis + advmod + mark, similarly to English SentA so SentB, if there is no subordinator and otherwise with advcl:

החוק לא אסר זאת, הרי שזה חוקי
root(asar)
parataxis(asar,xuki)
advmod(xuki, harei)
mark(xuki, she)

מאחר שהחוק לא אסר זאת, הרי שזה חוקי
root(xuki)
advcl(xuki,asar)
advmod(xuki, harei)
mark(xuki, she)

Maybe not ideal semantically, but causes the fewest problems/inconsistencies?

**Comment by Hilla-Merhav** [comment]
@amir-zeldes
Maybe I enter here too deep to the information structure level, but I feel that the first sentence – 
החוק לא אסר זאת, הרי שזה חוקי
is also a conditional sentence. Even though we don't have an explicit אם, I think we feel it implicitly. The question is – are we allowed to infer a conditional meaning from a sentence with no אם? I think it's very common in Hebrew. For example –
 
**שברת – שילמת**

Intuitively I would analyze it as a conditional sentence – שילמת is the `root`, שברת is an `advcl`. (**אם** שברת – שילמת!) 
Does it make sense? If it does, this is how I feel about this sentence: החוק לא אסר זאת, הרי שזה חוקי. 

My feeling that הרי ש is always the opening of the main clause also based on this section in Rav-Milim:
![image](https://user-images.githubusercontent.com/90029994/137293625-6bfd96b7-1c31-47fb-827a-89bb32354ba9.png)


But tell me if I am going to deep to the information structure level – I know we deal only with syntax for now, and maybe my reason is indeed beyond the syntax level.

**Comment by amir-zeldes** [comment]
I think this is on the level of discourse relations (information structure is yet another issue, things like topic/comment, focus, information status), but indeed UD does not seem to recognize such implicit discourse structures as syntactic facts. 

For example, for English sentences like "I wanted to, so I did it", we use parataxis, even though there is a clear causal relation. Because there is no "because", we don't get to treat it as advcl. Some languages have pretty strong marking for subordination and give cross-linguistic evidence for the validity of this decision, in case that helps make the argument more convincing. For example in German, conditional or causal clauses are normally verb final, but implicit structures without a complementizer don't trigger that word order:

Ich wollte es machen, also habe ich es gemacht (both clauses have verb-second order, parataxis)

Weil ich es machen wollte, habe ich es gemacht (verb-last triggered by "weil" = 'because', advcl)

**Comment by Hilla-Merhav** [comment]
@amir-zeldes Thank you for your interesting explanation. :) I see know how `mark` can serve us. I am analyzing it as you wrote, `advmod`(**_predicate_**, harei)+`mark`(**_predicate_**, she).
