### ISSUE TITLE
FIXED EXPRESSIONS LIST rearranged

### ISSUE THREAD

**Issue by strasss** [IAHLT/UD_Hebrew#29]
Hello everyone 

@amir-zeldes 

I've rearranged the fixed expressions list (here following) as it was quite messy and the items are unsearchable.
I divided the expressions into groups by the deprel they are governed through.
Before I replace the lists in the actual document I'd appreciate if you go over it and see if I got it all or mostly right - in terms of the expressions themselves and the deprel they are governed through. 
Attached is a .doc of the list 

o	Nouns
אב טיפוס | שח מט

o	Prepositional ( `case` )
אל תוך | באשר ל | ב העדר | בהתבסס על | ב מהלך| ב מסגרת | בניגוד ל | חוץ מ | ל טובת | ל משך | לבד מ | למעלה מ | מ אז |  מ זה | 
מ לפני | מ עבר ל | מעל ל | עד כדי |  עד ל | עד לפני | 
על אודות | על אף |  על גבי | על ידי | על כן | על פי | על פני | על רקע | 
תוך כדי | ב דומה ל | ב שונה מ | ב המשך ל | ב השוואה ל | ב התאם ל | 
ב התייחסות אל | ב יחס ל | ב קשר ל | ב יחד עם | ב נוסף ל | ב תמורה ל | מ סביב ל | עד כדי | ב נוסף ל | ב נוסף על |

o	Conjunctions (`mark`)
אם כי | אף על פי ש | אף ש | בגלל ש | כדי ש | כפי ש | כשם ש | לפני ש | למרות ש | מאחר ש | מפני ש | משום ש | עד ש | כך ש | היות ו | היות ש |  לאחר ש | על מנת ש | תוך ש | כל אימת ש |  לא בלבד ש | עד כדי ש | מכיוון ש | כיוון ש |

o	Coordinations (`cc`)
ו אולם | ו אילו

o	Adverbial (`advmod`)
יותר מ כל | יותר מדי | יחד עם זאת | יתר על ה מידה | יתר על כן | יתרה מ זאת/זה | כל כך הרבה | קודם ל כל | קודם ל כן | קרוב ל וודאי | ו כו | ו כדומה | ו כד' | עד מאוד | אחת היא | אי פעם | אין סוף | הוקוס פוקוס | מ זה כבר | יותר מ | פחות מ | כל כך | לא אחת | לא כבר | סוף סוף | עד כה | קודם כל | ראשית כל | אחת ו ל תמיד | באמת ו בתמים | בראש ו בראשונה | די ו הותר | ו כך הלאה | ו תו לא | כלל ו כלל | לא מ כבר | 

זה מ כבר | מ עתה ו הלאה | שוב ו שוב | תיכף ו מיד | כך או אחרת | כך או כך | פחות או יותר | ב בת אחת | יתר על ה מידה | מדי פעם | מדי פעם ב פעם | פעם אחר פעם מ פעם ל לפעם  | כ פעם ב פעם | ב דרך אגב | ב דרך כלל | בכל זאת | ב כלל זה | כלל ו עיקר | זאת ו עוד  | ו עוד כהנה ו כהנה | פה ו שם | מ אז ו מ תמיד | עד כדי כך | עד כה | יחד עם זאת | ב כל זאת | ב כלל זה | ב נוסף

[guidlines fixed list-omer 14.10.21.docx](https://github.com/IAHLT/UD_Hebrew/files/7343806/guidlines.fixed.list-omer.14.10.21.docx)

**Comment by amir-zeldes** [comment]
I have to say I'm not crazy about nouns being fixed like shax-mat, since otherwise we would have a very large list of candidates (what about shesh besh?) and the fixed list should ideally be enumerable, so this should maybe just be flat?

Otherwise the list looks mostly right, I only had doubts about these, especially coordinations:

באמת ו בתמים (why not analyze as conj?)
הוקוס פוקוס (maybe also better as flat)
כך או אחרת / כך או כך (also looks literally analyzable as conj)
מדי פעם | מדי פעם ב פעם | פעם אחר פעם מ פעם ל לפעם | כ פעם ב פעם
כהנה ו כהנה
זאת ו עוד
שוב ו שוב | תיכף ו מיד
מ עתה ו הלאה
כל כך הרבה (this looks totally compositional to me)

**Comment by Hilla-Merhav** [comment]
@amir-zeldes 
I guess expressions like באמת ו בתמים were in the list because of the HTB. Do you want me to enter the expressions you elaborated to the "amending the HTB" list? I guess each one has one occurrence or so… and then we can remove it from the old `fixed` expressions list :)

**Comment by amir-zeldes** [comment]
Yes, honestly I think it's a good idea to reform these, because the list is getting out of hand, and other UD languages don't typically have such large inventories of `fixed`. The more we can analyze using the surface syntax the better IMO.

**Comment by Hilla-Merhav** [comment]
@amir-zeldes 
I added it to the ["amending the HTB" list](https://docs.google.com/document/d/1_GaUIwt0kiSh3AwE8B47m7ARNF-PHPxC/edit), we'll soon fix the Guidlines too :)

**Comment by Hilla-Merhav** [comment]
@amir-zeldes

If we are already amending the HTB, can I suggest removing also 

ו כו
ו כדומה
ו כד'
פחות או יותר
פה ו שם
מ אז ו מ תמיד
בראש ו בראשונה

which on one hand they all very easy to analyze using the surface syntax, and on the other hand each one has 1-3 occurrences on HTB (so we can fix it quickly)?

**Comment by amir-zeldes** [comment]
Absolutely, thanks for suggesting this. I think initially I was very conservative looking at these things since I didn't expect we'd do manual revisions on the complete HTB, but re-thinking this, HTB is actually just a fraction of what IAHLT has in the pipeline, and you're right - it's not that much work given the amount of occurrences. 

This will all improve the corpus by a lot in my opinion!
