### ISSUE TITLE
Nitpael - how should we tag based on productivity, structure and usage?

### ISSUE THREAD

**Issue by IsraelLand** [IAHLT/UD_Hebrew#33]
Hi @amir-zeldes

We've had some cases now of originally Mishnaic Hebrew binyan nitpael, 
e.g. נתגלו מקרים
initially thought to be rare to warrant an issue, its productivity in MH questionable, we now deal with a bunch of law-related stuff, and we **do** see it used in some contexts - what binyan should we tag?

1. I initially thought this not to be very productive, but still its own binyan which isn't on the list, and did not tag for binyan
2. As we now see it used more, we can add it to the list, assuming it's productive enough
3. Some opted for hitpael altogether, as nitpael is the Mishnaic passive, a role MH hitpael often fills

Structurally, nitpael is not hitpael. If we take a strict morphology-structure based approach (similar, I think to what we do with masculine verbs not necessarily denoting males), we'd need to add nitpael to the list of binyanim.

Usage-wise, it's more complicated. Nitpael seems mostly passive-incohative, like hitpael, but hitpael, certainly in MH, is broader, used in a variety of contexts nitpael seems not to be used in MH (reflexivity, etc.), 
התנשקנו-*נתנשקנו
התגלחתי-?נתגלחתי
התגעגעתי-?נתגעגעתי

Productivity aside, if we assume this to be prevalent enough to add HebBinyan anyway,
we can either go the morphology way and add nitpael to the list, or otherwise equate this to hitpael if we deem the usage as the same.

Thank you!

**Comment by amir-zeldes** [comment]
I would vote for adding it as a possible value. I could imagine people interested in it who would appreciate being able to find examples easily.

**Comment by IsraelLand** [comment]
Great. Thank you!

**Comment by Hilla-Merhav** [comment]
@amir-zeldes

I have found recently Mishnaic infinitive in my batch – ליתן instead of לתת (it's a very legal article on Wikipedia), used in the same environment of any other infinitive

 אינטרס זה גובר על המשקל שיש **ליתן** לחתירה אל האמת העובדתית

At first, I thought I should treat it as a regular infinitive. But if we want to indicate in our analysis that there is a difference between Mishnaic Hitpael (נתפעל) and the regular התפעל – is that relevant also to the difference between the regular infinitives לתת, ללכת and the Mishnaic infinitives ליתן, לֵילֵך etc?

**Comment by amir-zeldes** [comment]
I don't think it's a binyan... I mean, its lemma would still be "natan" right? So you have two options: mark it as a foreign word (and therefore no binyan), or treat it as a (foreign-inspired) native/integrated word form, which is an alternative infinitive of a regular PAAL verb (just like English has both "slayed" and "slew" as past forms of "slay")

**Comment by Hilla-Merhav** [comment]
@amir-zeldes 

I didn't mean it's a banyan, just a Mishnaic form of infinitive. At first I wanted to analyze it as we analyze לתת, VerbForm=Inf as usual, because I think the only difference between לתת and ליתן is the form of Hebrew that they belong to / the register. 

I thought the same about נתפעל – as a Mishnaic form of התפעל. But if we are adding Nitpael _beside_ Hitpael, should we add a value for alternative infinitive - for example, VerbForm=MishnaicInf, beside the regular Inf?

**Comment by amir-zeldes** [comment]
No, I don't think it's the same, because nitpael is a whole paradigm (it has a separate form for many persons, a separate lemma), whereas this is just one alternative form in the paradigm. I think it either is a regular alternative (fancy) form that is now considered part of Hebrew (then it's just VERB, Inf etc.) or it's a loan word, in which case it could still be a loan VERB, but it would not have the same lemma and no binyan (or it's a totally foreign piece of text, then tag X, but I don't think that fits here)
