### ISSUE TITLE
The structure `AL + LE + NOUN + Inf`

### ISSUE THREAD

**Issue by Hilla-Merhav** [IAHLT/UD_Hebrew#36]
Hi @amir-zeldes

How we should analyze the structures – 

 **אל** **ל**בית-משפט זה **לאמץ** פרשנות זו
**אל** **ל**רגש **לגבור** על השכל ?

**Comment by amir-zeldes** [comment]
Basically it's either a case of seeing it as a negation predication about a clausal subject (viewing "al" as the root), or we view "al" as a regular negation, like in a negative imperative, in which case the infinitive is the root and "al" is advmod. I think the latter interpretation is preferable, and then I would probably just stick the le- phrase as obl to the infinitive.

**Comment by strasss** [comment]
I vote for the first option (that's what I thought initially:) - more than anything, because I think it would be strange to treat רגש as the oblique argument of the verb while semantically it's actually its subject.

Somewhat similarly, if it were על הרגש לגבור על השכל, the PP also wouldn't be an oblique argument of the infinitive, but actually govern it through 'csubj' itself, if I'm not mistaken.

**Comment by amir-zeldes** [comment]
Yes, the latter part is true, so if you want it could be csubj here too; but I think רגש would still be oblique in that analysis as well, since it has the preposition. I think analysis 1, with al as the head and csubj, looks like this:

root(al)
csubj(al, leamets)
obl(al, beit)
case(beit, le)

Are you saying beit should be nsubj of leamets?

**Comment by strasss** [comment]
No, I meant just what you specified in analysis 1 👍

**Comment by Hilla-Merhav** [comment]
@amir-zeldes If we choose this way, should we tag אל as a VERB? What morphological features we should assign to it?

**Comment by amir-zeldes** [comment]
I just learned yesterday that Arabic does weird stuff like that due to grammatical traditions where some similar particles are 'pseudo-verbs'. But no, I wouldn't have expected that. It's not totally ridiculous, since it's almost like a negative imperative, but the same word in imperatives proper is tagged ADV in HTB, and I'm not sure we want to claim this is a different word from אל in אל תפחד. So I guess I would vote to keep it as ADV for simplicity, though in some way it is a sui generis.

**Comment by Hilla-Merhav** [comment]
@amir-zeldes I guess if it stays ADV, we make it `aux`? Or it can be ADV and `root` that governs `csubj` at the same time?

**Comment by amir-zeldes** [comment]
The analysis @strass supports is ADV as root with csubj - nothing needs to be aux IMO. The alternative would have been root for the verb and al as advmod (a standard negation), but that would mean we understand it as a kind of 3rd person imperative or jussive ("may it not be...!")

**Comment by Hilla-Merhav** [comment]
@amir-zeldes sorry, I misunderstood and thought the consequences of `root`ing אל is tagging it as a VERB. So a `root` ADV that governs a `csubj` and an `obl` is agreed?

**Comment by Hilla-Merhav** [comment]
@amir-zeldes Also, there is a controversy on Slack whether we should assign to it a Polarity=Neg feature. Should we?

**Comment by amir-zeldes** [comment]
> So a root ADV that governs a csubj and an obl is agreed?

Sounds good to me. Polarity=Neg makes sense as well.

**Comment by NathanD38** [comment]
@amir-zeldes 

Regarding Polarity, I recall a thread on Google Docs Guidelines, in which you argued that, to assign
a polarity value, we require contrastive tokens. So we can have a two-way contrast between 
hino/eino, ken/lo, and a three-way contrast between yesh(no)/ein(o)/haya.
If we cannot find a contrastive token for "al", should it receive a polarity value?

**Comment by amir-zeldes** [comment]
For items like plain negations, such as 'no' or 'not', which are usually assigned polarity in UD, I think the normal situation is that the 'opposite' is to just not have them. So "lo" is polar, because you can say "halaxti" vs. "lo halaxti", with the understanding that "halaxti" is something like "ken halaxti". For copulas this is a little complicated if they have negations and negative correpsondences (think about laysa vs. ma kaana in Arabic).

In this particular case I understand your unease, because you can say "ligbor al ha-sexel" (kind of an imperative-like infinitive), but you can't say "la-regesh ligbor al ha-sexel". At the same time, the word "al" (with aleph) normally takes polarity as the negative imperative marker, so it would be a little strange not to have the polarity value here, where it looks like the same lexeme, and has the negative meaning. So I guess I find it hard to defend on strict definitional grounds, but it still makes sense to me that it would be a negative item. Otherwise we are not marking that this is a prohibition anywhere...

**Comment by NathanD38** [comment]
@amir-zeldes 

That's true! It would not be differentiated from the affirmative without the Polarity value.
I stand corrected! :)
