### ISSUE TITLE
"let us"-"bou" Hebrew construct

### ISSUE THREAD

**Issue by IsraelLand** [IAHLT/UD_Hebrew#38]
Hi @amir-zeldes

We've stumbled upon these cases, bou+Verb -
`"בואו נעשה את הניסיון", "בואו נביא את הבשורה"`

Quite common, but maybe not so much in the old Haaretz HTB literary style...
It seems that the options for deprels are -
1. `xcomp `- this is the the English GUM "let's" usage afaic and should reflect some sort of predication. Question is, if it fits the Hebrew usage
2. `advcl `
3. `aux `- some sort of an aux structure, like "rotze lalechet" reflecting the grammaticality of "bou/boi/bo+conj. verb" structure, though I'm not sure it's quite the same, it's tough seperating semanticity from function in this case
4. `discourse `- kind of a discourse marker like "shma, tire"
5. or just go the (easy?) `dep `or `parataxis `route

I'm undecided between 1 and 3, as I think that "bou" definitely serves a grammatical structure, which involves some 'sub-predication' perhaps
Thank you!

**Comment by Hilla-Merhav** [comment]
@amir-zeldes
I don't think it's `xcomp` because I don’t think it's a core argument, syntactically (in English it is `xcomp` – **let's** is a contraction of **let us** ---> let's do it – let us do it - but in Hebrew it's different).
We don't analyze יצא לעשות as `xcomp`, but as `advcl`, so I think when we analyze בואו לעשות –  (bou, laasot) should be `advcl` also.
![image](https://user-images.githubusercontent.com/90029994/141308798-80814197-b8b8-4680-bf98-ac668300329c.png)

As for בואו נעשה I am not sure whether it's `advcl` or `parataxis`, or maybe it's better נעשה would be the head somehow.

**Comment by IsraelLand** [comment]
I see. Personally I do think it's a core argument, or a head in itself, as `בואו נעשה` as a verbal phrase is completely different than `נצא לעקוב`, where in the latter you actually **go out &/then track**, whereas with the former the doing is key, i.e. no one is actually coming, just doing (basically, Modern Hebrew grammaticalization)

**Comment by amir-zeldes** [comment]
This looks to me like what is usually referred to as a serial verb construction, and is also attested in English in things like "to go do something". Some languages use a special type `compound:svc` for these, see the guidelines here:

https://universaldependencies.org/u/dep/compound-svc.html

Relevant discussions:

  * For English/Hebrew : https://github.com/UniversalDependencies/docs/issues/323
  * Compound verb analysis: https://github.com/UniversalDependencies/docs/issues/386
  * Recent discussion in Indo-Aryan: https://github.com/UniversalDependencies/docs/issues/819

My reading of the situation based on the Hebrew speakers who chimed in, and the comparison with English, is that the consensus favors `conj`, and in any case not `advcl` or `xcomp`, because you can insert 've'. I think the languages that have opted for `compound:svc` are the ones in which this is extremely productive and regular, verging on an auxiliary as part of a paradigm, which forms something like a new "cohortative verb" complex, or "desiderative" (often with "want"), "benefactive" (often with "give") etc., whereas in Hebrew I think it's still more or less a transparent coordination with pragmatic constructional flavor.

**Comment by IsraelLand** [comment]
Huh, didn't even think of conj., and that it can be used with a coordinator, so I guess conj. makes sense (Though still no one is actually coming, only doing, but it holds true for the English as well)
The compound nature of the phrase isn't entirely shown imo by conj either, but I agree it's still much more transparent in Hebrew, still.
Thanks.

**Comment by Hilla-Merhav** [comment]
@amir-zeldes
Thanks! Seems reasonable. So `conj` for (bou, naase), and what about (bou, laasot)? We can't insert 've', and the example from the guidelines seems comparable to me, so I think `advcl` is right for infinitive after בא, בואו: 
![image](https://user-images.githubusercontent.com/90029994/141346693-e21338ea-62d5-4b7f-8fa3-7e52b9df25f3.png)

הוא בא לטורקיה לעקוב אחרי נבחרת הנוער
הוא בא לטורקיה (כדי) לעקוב אחרי נבחרת הנוער
בואו לעשות את הניסיון
בואו (כדי) לעשות את הניסיון

**Comment by amir-zeldes** [comment]
Yes, this seems normal: if "kedey" is possible, it's a purpose advcl, otherwise it's an xcomp infinitive (like "nasu la'asot/xcomp")
