### ISSUE TITLE
Treatment of formerly-Vnoun tokens

### ISSUE THREAD

**Issue by IsraelLand** [IAHLT/UD_Hebrew#40]
@amir-zeldes

I've been wondering how to treat certain aspects of base forms, now that we've done away with the Vnoun feature.
`פניצילינים משמשים למעשה הפטנים ב היקשר ם לחלבונים מתמיסה לא מזוקקת`
1. Will the lemma just be the base form itself `היקשר`? Are all the regular features of nouns present (though it is quite absurd to say `היקשר אחד, שני היקשרים`)?
2. More importantly, would the verb warrant an advcl, meaning - 
   advcl (meshamshim, hikasher), or rather an obl?

This is mainly based on your emphasizing that advcl's are the regular clausal non-core deprel.
(as well as [this example](https://universaldependencies.org/u/dep/advcl.html), though I'm not sure it's completely the same, the clause lacks a verb as well)
![advcl-5](https://user-images.githubusercontent.com/91226299/142782309-0eda1c57-cbf0-4008-8986-76b37bfedcc5.JPG)
  
In any case us deciding base forms "not to be verbs" anymore, is great (TBH Vnoun constructs were a bit weird), but the forms still retain their verb-ness, and the purposed rephrased `פניצילינים משמשים ... **בהיקשרות שלהם** לחלבונים מתמיסה לא מזוקקת` seems off.

Thank you

**Comment by IsraelLand** [comment]
Hila directed me to the [summary ](https://github.com/IAHLT/UD_Hebrew/issues/21)she did after the Vnoun change was decided. 
So it seems these two questions remain,
1. Should we tag for gender & number?
2. I'd be happy if you could explain what is the difference, if any, between the general UD interpretation of `with the kids in school, I have plenty of time` and ours. `פניצילינים משמשים הפטנים. [עם היקשר ם לחלבונים] ` doesn't seem structurally different, I'd appreciate your take on it.
Thanks.

**Comment by amir-zeldes** [comment]
My TL;DR: I think because we decided these are nouns, then they should normally have Gender and Number, and the only way for them to be advcl is if they are predicates in a nominal predication. 

About the morphology, I agree it's a bit odd, but they seem "more Masc Sing than anything else". It would be rather difficult for me to say, but I would sooner say "be-hikashra-m ha-maft'ia le..." than "be-hikashra-m ha-mafti'a" (Fem) or "be-hikashra-m ha-mafti'im" (Plur) or anything else. So I think with no contradictory evidence, I would assume they are Masc and Sing.

About the deprel, I think there is a difference to the "with" example - although "be" could take the place of the `mark` here, we don't have `nsubj`, which would really be needed if you wanted to think of this as `advcl`. If you could say something like:

  * הפניצילינים פועלים החלבונים בהיקשרם לתמיסה

Or:

  * הפניצילינים פועלים בהיקשרם החלבונים לתמיסה

Then there would be a case for advcl. But the only way to express the agent of the nominalized verb is using smixut:

  * הפניצילינים פועלים בהיקשר החלבונים לתמיסה

And since we wanted these things to be fundamentally nouns, it seems inconsistent to ignore the smixut here and call it `nsubj` (which would justify `advcl`). I think the most straightforward analysis is to treat it as an agent compound (like the non-canibalistic reading of בישול האם)

**Comment by IsraelLand** [comment]
Yeah, I see how's that more consistent overall. 
I still wonder what happens in Arabic, both in an academic manner and for when we'll need it, but for our case here, I get it...
Thank you!
