### ISSUE TITLE
Clauses and their headlines

### ISSUE THREAD

**Issue by Hilla-Merhav** [IAHLT/UD_Hebrew#6]
@amir-zeldes
Some clauses in Wikipedia include headlines, especially when it comes to a list of clauses. In my batch I have three examples:
[המשותף לחוקי היסוד:]
•	**צורה** - בכותרת יצוין "חוק יסוד", ניסוח כללי כיאה לעקרונות וערכים, היעדר תאריך החקיקה כדי להדגיש כי הערכים הם מעבר לזמן ומקום.
•	**מעמד** - חוקי יסוד הם בעלי מעמד (על) משפטי עדיף על פני חוק רגיל. כאשר חוק רגיל סותר חוק יסוד הוא עלול להיפסל בידי בג"ץ.
•	**תוכן** - חוקי יסוד אמורים לבטא את שני עקרונות היסוד של המדינה: יהודית ודמוקרטית, לבטא ערכים מרכזיים, להגדיר את הרשויות והיחסים ביניהן ולעגן את זכויות האדם, האזרח והמיעוט.

I wonder whether the root is the headline or the predication, and what is the connection between the headline and the predicate.

**Comment by amir-zeldes** [comment]
In at least some UD TBs, block elements like list items are separated into separate sentences for convenience, and maybe it's worth doing here too (otherwise this is a rather monstrous sentence). If we keep it as one sentence, I would say its root is "tsura", with nsubj "meshutaf", and the next bullet point roots attached to it as `parataxis` or maybe `list`. But really it would probably be better to just consider these as separate sentences.

**Comment by Hilla-Merhav** [comment]
@amir-zeldes Oh sorry, now I realize my question was unclear – the bullets are indeed separated into separate sentences, and I wonder how should each inner analysis look like – the challenge is the mini-headline of every bullet (צורה and the following clause, מעמד and the following clause).
I wonder whether the root is the headline or the predication, and what is the connection between the headline and the predicate.
![image](https://user-images.githubusercontent.com/90029994/133308601-a5e05295-ada4-4b4f-bda0-b616a0b91120.png)

**Comment by amir-zeldes** [comment]
I think it's not really a predication, so I would say it's parataxis - syntactically these two things just stand next to each other.
