### ISSUE TITLE
Uniformity of tagging across Abbr. expressions

### ISSUE THREAD

**Issue by IsraelLand** [IAHLT/UD_Hebrew#62]
@amir-zeldes

These few cases hint at some general issue that I think is quite prevalent in Hebrew (Does English etc. help in the matter?) - 
1. The expression ע"ש is ADP, while the compositional על שם seems not to be. "Shem" here seems quite transparent and comp., so we tend not to "fix" this expression (al+shem as one ADP), but to treat "shem" as a noun. That said, Fixed would be more in line with ע"ש.
2. stuff like וכד' - Some of us would swear by ADV. While for וכדומה - a compositional adj - ka+dome. Again, a different tagging for the exact same thing. I for one, see an ADV for both - I don't see why we would re-seg. כדומה but not כלומר (ke(mo)+lomar).
3. Finally, this begs the question of זאת אומרת, which is very similar to כלומר. I would argue most would treat it quite compositionally, thus parataxis, zot+omeret(verb) and so on. But what about the very prevalent colloquial זתומרת - this is now one word, VERY similar to כלומר. Would we go for a different tagging?

I'm not necessarily looking for answers regarding the above (though Netanel did bring up the 1st one), more for a guideline -
1. I find it odd that EXACT same expressions would get completely different annotations. That said, if we decided "shem" is transparent (almost, not in "leshem?") anywhere else, to fix it here would be another non consistent tagging.
2. ADV being a dumping ground of sorts to any problematic token is kinda slippery-slopey imo

All in all, what do you think should "overpower" what - the desire for uniformity of same expressions (על שם וע"ש always as one adp), 
or uniformity to the "general framework", with the side effect that Abbv. expressions deviate wildly from their counterparts.
(Sometimes these abbreviations are very intricate, and nothing but ADV is possible. But not most of the time.)

Thank you

**Comment by amir-zeldes** [comment]
> Does English etc. help in the matter

Actually that's [a whole can of worms](https://github.com/UniversalDependencies/docs/issues/820)

> ע"ש

If you make this fixed keep in mind you will quickly run into the double possessive "al shmo shel"

> I find it odd that EXACT same expressions would get completely different annotations

I feel your pain, but this is very much the standard practice in current corpus data. Although everyone sort of agrees that spoken language has some kind of primacy, most CL work assumes that tokenization should be 'convenient', so in English you get a single token "e.g.", but if anyone ever spells out "exempli gratia" it will be two tokens.

That said, if it's a theoretical comfort, you could argue from a constructivist perspective that many abbreviated forms are entrenched and develop a life of their own. I think it would be quite difficult to use "exempli gratia" interchangeably with e.g., for example - it's fossilized now, and most people don't know what it abbreviates. I'm sure I've heard people literally say `[vexado]`, maybe not 100% seriously and on purpose trying to evoke written language, but it's a thing.

So my short answer would be: accept that acronyms are tokens and tag them as appropriate. Mostly people tag them in UD based on the head POS, so a noun acronym is tagged NOUN, but "lmao" might be tagged VERB if appropriate. That said, for conventionalized forms you might see people tagging by function, so "lmao/INTJ", and for PPs, because "NOUN" would be odd, you see people tagging ADV (basically saying, it's an oblique prep+NP, which, without a 'case' marker, is basically an adverb).

Finally "זתומרת" seems non-established in writing to me, and is really just a reduced phonetic form, so I would be tempted to tokenize as זת + ומרת, SpaceAfter=No and lemmatize and tag as usual (similar to English 'twas = it + was), plus add CorrectForm to normalize.

**Comment by IsraelLand** [comment]
Oh, I just meant English and so on, my bad, but I guess etc. vs. et cetera IS a good example...
Yeah I see where you're coming from, they tend to get a life of their own at some point. 
I don't think this is valid for ע"ש, which is always broken apart when spoken, but I get the spelling-tagging constraints.

As for זתומרת, I totally get that, just why would it be different than כלומר vs. כ לומר? 
Should normativity or "establishedness" be a criterion in differentiating the two?
I see the similarity with 'twas, it's just that, is CorrectForm REALLY the actually applied\wanted approach? 
It's one thing to re-seg. to it-was, it's another to erase 't as a form altogether, which seems an awful lot like normalizing to me.

**Comment by amir-zeldes** [comment]
> As for זתומרת, I totally get that, just why would it be different than כלומר vs. כ לומר? Should normativity or "establishedness" be a criterion in differentiating the two?

Yes, definitely. I mean, many words in each language have a more or less transparent internal structure. If you analyze כלומר internally, then you can also split the infinitive -l- inside it and make it into a preposition (this is what English to-infinitives do after all), and there is really no theoretical limit. The only reason we consider לבד to be an adverb is that we can no longer see a noun בד in there, but it is conceivable to split it, right? I mean, it would elucidate the connection to the root in בודד. So a word being 'established' seems to be part of the tokenization decision, and I think כלומר is probably on the 'frozen' side of that boundary.

> is CorrectForm REALLY the actually applied\wanted approach? It's one thing to re-seg. to it-was, it's another to erase 't as a form altogether, which seems an awful lot like normalizing to me.

`CorrectForm` is just a MISC annotation, so we are not actually normalizing the token form itself. You can still see that it was realilzed as זתומרת in the FORM column, so that should be OK no? And it helps establish the connection with the normative spelling, as well as opening up NLP applications with automatic normalization/automatic grading/grammatical error correction, or linguistic studies that need to be able to generalize over citation forms.

**Comment by IsraelLand** [comment]
Yeah I see what you mean, normativity bordering on transparency. Not the most frozen there is imo, but I see how intertwined they are.

I actually thought CorrectForm is more of a "this is the actual token that should have been here and taken into consideration", while the original form is a sort of documentation. 
Especially when dealing with gender issues, I thought it essential that the typo be eradicated, for lack of a better word, so that "the model" wouldn't "learn from mistakes" - assume female forms for masculine and so on.

I see now that there's more to it. We've actually been wondering about _some_ features, and their supposed applications, but I think that's a bigger discussion for another day/issue :)  (e.g. tagging for verbs is clear - they have very defined behaviour, like environments, usage etc., while stuff like VerbType=Mod seem a bit vague for Hebrew)

Thank you

**Comment by amir-zeldes** [comment]
Sure, happy to talk about it more as well - for MISC attributes, this page is useful to get a first idea of what some things are supposed to be doing: https://universaldependencies.org/misc.html
