### ISSUE TITLE
Grammatical vs. underlying vs. morphological gender

### ISSUE THREAD

**Issue by IsraelLand** [IAHLT/UD_Hebrew#65]
@amir-zeldes
ננסי פלוסי, ראש בית הנבחרים הדמוקרטית
Nancy Pelosi, democratic.fem head.? of House of Representatives

What gender should "rosh" have? 
Its grammatical gender is masculine, it doesn't have derivational feminine morphology (the introduced f. counterpart ראשת)
yet its underlying gender is feminine.

This can happen when animateness is introduced into the mix, knowing the noun is gender X, but since the referent is a living human being of gender Y, agreeing with the noun as if it's gender Y. That is even with no explicit Y-gender derivation.

But not always, some of the ones I can think of rn are -
(+animate) kolega madam zohar, (-animate) subaro 
e.g.
יש לו קולגה מוכר שעוסק בזה
זוהר הזאת, תלמידה ממש טובה
הוא קנה סובארו חדשה, מהירה ממש
known.masc colleague.fem? ,  new.fem subaru.fem? and so on

It seems UD mainly treats morphology, not so much semantics. 
While "kos" is grammatically feminine without need for overt feminine morphology, which is fine,
It'd be harder to derive a feminine tagging for masc. "rosh", without, well, feminine derivation. 
They only agree in the speaker's mind, because they have Pelosi's image in mind.

Thank you

**Comment by amir-zeldes** [comment]
Some of these cases are well known in UD (e.g. Polish also has kolega) and they are tagged based on agreement (so Masc for a male colleague)

"rosh" is a bit more complicated since you have to decide whether there is a canonical counterpart "roshat", and if so we could say this is still a Masc form since the speaker could have chosen "roshat" if they wanted to. This is difficult to decide based on 'mind-reading', so maybe in the absence of clear Fem agreement I would just act robotically and assume that "rosh" is morphologically Masc until there is clear evidence otherwise. 

Finally for Subaru it is clear that it is Fem in this context, and BTW German behaves the same way (all cars are Masc because "Wagen" is Masc., and in Hebrew it's presumably by analogy to "mexonit").

**Comment by IsraelLand** [comment]
Yeah for Wagen vs. mexonit this is more straightforward (though toyota would always? be fem. while mercedes doesn't have to be). 
But for rosh there's a more dominant natural gender (i.e. masc) competing against the underlying one (fem. for women), than car brands (barring -a ending brands).

I did try looking for a Fem. Kopf (perhaps a colloquial fem. Mädchen) but couldn't find anything relevant. 
Too bad I did not think about Polish because it's quite a similar paradigm, at least for non native words ending in -a,

So I would go for a similar ראש בית הנבחרים הדמוקרטית as **Fem.**  if you could get behind this even in the absence of ראשת, which in any way is quite new neologism (the dichotomy obviously does not exist in the minds of some people).

Is the Arabic situation relevant at all, with مطار - مطارات or is it just like חלון-חלונות which is "feminine" only by suffix and not by agreement?

Thank you

**Comment by amir-zeldes** [comment]
On an ad hoc basis, Fem. is a valid analysis, it means you think this is a gender-flexible word, and here it is the Fem version.

The Arabic situation, and xalon, are both NOT feminine, based on agreement, though for Arabic the situation is complicated by classical Arabic's treatment of inanimate plurals as receiving feminine singular agreement. In any case, مطارات is either Masc. Plur. (if we want to treat it as morphologically plural), or Fem. Sing. going by agreement (if the language being analyzed obeys canonical classical grammar). I think there is no valid analysis in which it is Fem. Plur. just because it ends in -aat. For xalonot I see no option except Masc. Plur.

**Comment by IsraelLand** [comment]
I see. So what I'm going for, is if you think there is a classical treebank that would tag the Fem. Sing., going by agreement, even though the singular is Masc.? Though I'm not so sure we can draw any conclusions from it.
I think I'd go for Fem., considering. Thank you

**Comment by amir-zeldes** [comment]
Yeah, the Arabic situation is unusual and not really relevant here
