### ISSUE TITLE
ze - ze mikvar structure

### ISSUE THREAD

**Issue by IsraelLand** [IAHLT/UD_Hebrew#67]
Hi @amir-zeldes

לצד המחאה **זה השבוע ה-29 ברציפות**, דורשים הארגונים המפגינים שנתנצל

I'm not sure of this structure.
dorshim seems to be obl:tmod of "hashavua" (or mexaa?), that's fine.
But what about "ze" - it might be a regular determiner, fronted, so we get the meaning "dorshim hashavua haze, ha29 birtsifut".
But I don't think it is. It seems like an adv, ze=kvar, "kvar hashavua ha29 birtsifut".

It seems to be a shortening of sorts of "ze mikvar".
There are quite a few "mikvar" or "ze mikvar" in the old HTB, all of them either a long fixed adv, or a fixed dep, who aren't quite up to par today.
assuming this is the same structure, would a simple adv+advmod on the "ze" do the trick?

Thank you

**Comment by amir-zeldes** [comment]
Ooh, this is a nice one!

I think there are two basic ways to behave here: either we take a literalist view, which views "this is the week" as the actual root predicate (which is of course pragmatically naive, but we are just doing syntax), or we can treat it as a parenthetical.

The naive reading would be identical to 'ze ha-shavua ha-29 **she**...'. The possibility of 'she' is important, because it would make the rest into an `acl`:

root(shavua)
nsubj(shavua,ze)
acl(shavua,dorshim)

This seems pragmatically wrong here, but if the sentence was the following, I think we wouldn't have a choice:

  * זה השבוע ה-29 שהארגונים דורשים...

Alternatively, if we are happy to give this case a different analysis, which is maybe possible due to the lack of 'she', then we can to it as a parenthetical:

root(dorshim)
obl(dorshim,mexaa)
case(mexaa,letsad)
parataxis(dorshim,shavua)
nsubj(shavua,ze)

This seems more pragmatically appropriate, at the cost of making the structure different from "ze-hashavua...she".

**Comment by IsraelLand** [comment]
So in either case you see it as its own sentence, interesting!
I think pragmatically the second one is better, "dorshim" seems more "head-y" to me, "ze hashavua" an unrequired addition, which I think the comma position might slightly support (over "letzad hamexaa,").
Obviously, a "she" would make all the difference.
Thank you!

**Comment by IsraelLand** [comment]
How about
בקופת החולים הנוהג קיים זה שנים

Would "shanim" be root, acl:relcl'ing "hanoag"?
I'm just not sure about the role of "ze" here, nsubj, some sort of adv? on top of that
הנוהג קיים שנים
works almost the exact same way, seems to be a shortening of מזה.
Thanks

**Comment by amir-zeldes** [comment]
I think either way you look at it, ze is nsubj to shanim. The only question is, is this the main clause? (meaning even without "she" we treat it like "she" is there) Or is it a parenthetical -> parataxis. The latter is more pragmatically adequate, but causes problems if 'she' is used. I think if you have "mi-ze", that just means you have a mark on the clause for which 'ze' is the nsubj.

**Comment by IsraelLand** [comment]
Thank you!

**Comment by IsraelLand** [comment]
Nevermind, you already answered that :+1:
