### ISSUE TITLE
Vnouns in סמיכות פרודה state

### ISSUE THREAD

**Issue by Hilla-Merhav** [IAHLT/UD_Hebrew#7]
@amir-zeldes

Following our correspondence in the Guidelines doc, I am coping your last instruction for the sentence: **החוק מעגן את היותה של מדינת ישראל מדינה יהודית** so we can resume this discussion:
**"et heyota medina yehudit" is an object clause introduced by "et", so et/SCONJ/mark is a child of "medina" (note it is not ADP/case, so we can tell it's not "et ha-medina")"**
Thank you very much, I have followed this instruction. But due to the fact the copula can't govern anything (as I understand) I still am not sure how should I analyze the סמיכות פרודה. 

My current (and wrong, I am sure) analysis is attached. I want to change it so the ישראל would be the nsubj of מדינה יהודית, but I am not sure how should I treat של, and the PRON ה too.

![image](https://user-images.githubusercontent.com/90029994/132980895-9eff2534-14af-4eca-9836-36e717207c5e.png)

**Comment by amir-zeldes** [comment]
I hadn't thought about this case... First of all medina could not be `obj` under this analysis, since it's a clause, so it would have been `ccomp` if anything. But you're right about it being a hard constraint that `cop` can't have children, so the only way to do this would be to make yisrael and the possessive "h" be children of medina somehow. If we did that, probably the best I can come up with would be either:

1. "h" is nsubj to medina, and yisrael is nmod:poss to "h"
2. "h" (or "yisrael") is nsubj to medina, and "h" is dislocated to medina

But both of these are so ugly I think it's better to give up and just treat "heyot" as a NOUN and medina as `xcomp` to it.

**Comment by Hilla-Merhav** [comment]
Thank you very much, this anlysis makes a lot of sense. Is it OK if I add it to the Guidelines?
![image](https://user-images.githubusercontent.com/90029994/133287698-201bac91-b6b5-4476-8817-2e1e79bb06ec.png)

**Comment by amir-zeldes** [comment]
Yes, I think this is the best thing we can do here. Language is just really complex... :)
