### ISSUE TITLE
Headless Relative Clauses in various syntactic positions

### ISSUE THREAD

**Issue by NathanD38** [IAHLT/UD_Hebrew#70]
@amir-zeldes

I would like to ask the correct analysis we should stick to regarding Headless Relative Clauses in various syntactic positions.

**Subject position:**

הרואה כבשים בשנתו ישן היטב.

Do we treat ro'e here as a NOUN or a VERB? If it's a VERB, should the 'heh' be considered an SCONJ, essentially a complentizer
of a headless relative clause (he who sees/the person who sees...)?
If we treat ro'e as VERB, and heh as SCONJ, do we have from our root a csubj or an nsubj?

csubj(nirdam, ro'e)
mark(ro'e, ha)

Or should this just be an intensified ADJ (ha-adam ha-ro'e), which can also go either way between a headless relative clause 
and a simple DET+ADJ?

**Object position:**

השר תיאר את הנאמר בפסקת החוק ביתר פירוט.

Here, our guidelines dictate taking the matrix clause's deprel over the subordinate's one.
So we have syntactically the same headless relative clause in obj position, (et) ha-ne'emar,

obj(te'er, ne'emar)
mark(ne'emar, ha)
case(ne'emar, et) [Case=Acc for et, right?]

but we do not assign ccomp or some other clausal deprel to this clause, due to the preference of the matrix clause's deprel.

**Oblique position:**

דיברנו אתמול על הנעשה למען ילדים בסיכון בבית הספר.

Here, too, our guidelines dictate taking the matrix clause's deprel over the subordinate's one,
having syntactically the same headless relative clause in obl position, al ha-na'asa,

obl(dibarnu, na'asa)
mark(na'asa, ha)
case(na'asa. al)

yet, we do not assign advcl or some other clausal deprel to this clause, again, preferring the matrix clause's deprel.
Or should we assign advcl, as a catch-all deprel for clausal obliques?

Now, the oblique position's analysis is at the moment invalid by some validation rule which (imho) needs revisting.
Unless the decision for oblique is different than that for obj, which does pass validation.

I believe there's a need for clarity and consistency in this particular construction of ha-beinoni.
The criterion to decide between DET+NOUN, DET+ADJ, SCONJ+ADJ or SCONJ+VERB (and their corresponding
deprels) should be laid out clearly, so that we might converge on consistent analyses as much as possible.

Thanks!

**Comment by amir-zeldes** [comment]
Hi @NathanD38 - this tension is often there with participles, and you're right, it's important to have clear guidelines. The easiest part to answer about the questions above is the combinatorics: there are really only two options (we can call them NOUN or VERB), and the one you choose dictates the answer to the rest of the questions (with a small caveat about free relatives).

For NOUN, everything would behave like a nominal: you would have nsubj, det, DET and everything else as expected. The main reason to disprefer this is the possibility of accusative objects on the participle in Hebrew (unlike the possibility of converting objects to "of" phrases in English).

In the VERB analysis, everything behaves like a verb is involved: yes, you would get SCONJ, and csubj, etc. This analysis is most convenient for handling the argument structure of the participle, but somewhat obscures nominal morphology (number, gender) being 'normal' here. However since we allow present tense use of participles as verbs with number and gender, I feel this is relatively minor, so I would probably prefer this for these cases.

Finally note that the 'promoting the matrix function' thing is just a general free relative thing, and would happen regardless of the analysis, meaning we analyze "et hana'asa" similerly to "et ma she-na'asa", except that the whole relative part is missing, so you are left with no choice but to promote the nested predicate to the object deprel (or obl if it's prepositional). I think this is more of a general promotion thing, and doesn't necessarily interact with the internal analysis of the predicate participle. Of course you can also have ccomps, but notice the difference in reading:

  * Siparti lo she hi ba'a
  * Spirati lo et ha-na'asa

The first is ccomp, and the object clause is a content clause. The second is an object NP, which could be replaced by a "ma she" free relative, but since it's reduced, we are left with no acl:relcl anymore. The object NP nature is discernible on the "et", and in transformational terms I suppse you could say this is like an empty "ma" head, governed by "et" and governing the free relative. Does that make sense?

**Comment by NathanD38** [comment]
@amir-zeldes 

It sure does!
Thank you for clarifying this.
I will ask Shira to modify the validation rule which currently prevents the oblique analysis with mark child.

**Comment by IsraelLand** [comment]
@amir-zeldes

What about,
כל ההכנות וההתרגשות של לחנך כיתה
Assuming this is acl (is it?), would "shel" be mark/SCONJ?

or,
בבחינת: "או שתסכימו או שתעזבו"
Would this be acl, rather than compound? despite the clear compound smixut morphology? 

Thank you

**Comment by amir-zeldes** [comment]
The first case is indeed mark/SCONJ, and fairly commong in other languages ("the difficulty of/mark/SCONJ doing that"). The second is indeed smixut, the matrix function `compound` takes precedence, and then the interior still gets a clausal analysis.

See related issues:
  * UniversalDependencies/docs#753 (compounds like must see-movie)
  * UniversalDependencies/docs#777 (coercing VPs into nominals)

**Comment by IsraelLand** [comment]
Great, this requires some validation tweaks so it's good to know. Thanks
