### ISSUE TITLE
"conjoining vav" - CCONJ vs. SCONJ

### ISSUE THREAD

**Issue by IsraelLand** [IAHLT/UD_Hebrew#73]
Hi @amir-zeldes

1.

In the [past ](https://github.com/ivrit/IAHLT-HTB-GUIDELINES/pull/4) we've agreed on a bunch of complex ADPs (which we later un-fixed some of, but they're still doing the jobs of ADPs in a broad manner), which contain ו' and -

These seem to be -

fixed -
היות ו (cf. היות ש )
היה ו 
הואיל ו

among the non-fixed (the ones in the link above) - 

במקרה ו
הלוואי ו

The last two seem to SCONJ according to what we've decided upon, as they're interchangeable to ש.
The first one seems to as well (even though it's fixed, so a fixed mark _can_ _be_ ADP+CCONJ, for example).

2.

Back then we've also discussed stuff like - מבנים **ו**בהם בור מים -

לאחר מכן ירדה למערה משלחת נוספת **ו**בה נציגי צה"ל והארכאולוג זאב ייבין.
בשנת 1922 מיפה הארכאולוג לואי-איג ונסאן ("האב ונסן") את המערה וכן תיאר מערה שמצא מתחת למבנים, **ו**בה מצבות ופתחים שונים למערות נוספות.
בעקבות זאת הושק ב - 28 בדצמבר אתר אינטרנט ייעודי שהוקם על ידי ארכיון המדינה , **ו**בו נחשפו ה פרוטוקולים של ועדות החקירה, אלפי תיקים ומסמכים .
הגיש נשיא מדינת ישראל, שמעון פרס, איגרת לנשיא אובמה **ו**בה בקשה מיוחדת 

Some of us remember that we decided not to treat those Vav's as SCONJ,
While some did just that - an extension of the above agreed-upon 1. tagging, possibly.

So -

a. It seems vav as a SCONJ, cf. במקרה ו is already decided upon (I'd assume you'd want these as SCONJ in the fixed expressions as well? e.g. היות ו ), so that's the treatment across the board **if we deem it that strcture** ?

b. What would you say about the above number 2. cases? Can they be SCONJ?
It's very nuanced, you could see a plain old CCONJ in them, but there might be more than that here.

I see them as part of the same process - while I could tag **all** of the above (even במידה ו) as a simple Conj+CCONJ,
there may be some deeper relativity here, like we decided in במידה ו cases. 
That seems to be what some prescribe here - "use במידה ש, not במידה ו" - there's relativity here, if not only by position.
I don't prescribe, but I aim to describe as true to structure as possible, and the boundary doesn't seem clear cut here.

I'd be happy to hear your take.
Thanks

**Comment by amir-zeldes** [comment]
Hi @IsraelLand , sorry for the slow reply due to travel over the holidays.

In general things change a little bit depending on whether or not this is part of a fixed expression. For tokens connected by `fixed`, UD takes the position that the POS tags can represent underlying morphological categories, which may be distinct from the putative morphological category of the complex expression. For example, as you know, `advmod` can only be used on an `ADV`, but there is an exception for fixed expressions: in English, "kind of" is `fixed`, and the first token is tagged `NOUN` (based on morphosyntax of the item 'kind'), but the whole expressin is attached as `advmod`, as if the whole thing is `ADV`.

A similar logic applies to coordinating conjunctions. For example, "as well as" in English is not tagged CCONJ in its components, but ADV+ADV+ADP, and yet it's attached as `cc` (as if the whole thing is CCONJ). For Hebrew, this would mean that we can do:

  * ho'il/SCONJ/mark ve/CCONJ/fixed

We could do the same with be-mikre ve, if we decide it's a complex SCONJ (then we would still tag ADP-NOUN-CCONJ, but fixed would indicate that the whole expression may have a different category).

For question 2, this is basically like the Arabic ħal clause - it's adverbial, and signaled by vav. I'm a little concerned there could be some confusion if we tag it as SCONJ, and it's not clear to me that morphosyntactically that's what it is, although I can see the argument for it. My gut feeling is to do CCONJ/cc and still tag the clause as adverbial (not `conj`), but if you all feel that SCONJ+mark is better, I would think that's really bad either.

**Comment by IsraelLand** [comment]
Thanks! Hope you had a good time.
Regarding be-mikre-ve, we've decided against fixing it, if not explicitly, but by way of the general aspiration to minimize the fixed list - especially for cases which make sense compositionally (obl(X, mikre), case(mikre,be)...).
So I don't think it's consistent to change it and start fixing it now, that's the gist I'm getting from the aforementioned [issue ](https://github.com/ivrit/IAHLT-HTB-GUIDELINES/pull/4)as well, where the vav is isolated from the bemikre.
So unless we start treating it as a complex, fixed SCONJ I assume they're still SCONJ, these vav's in isolation?

Regarding 2, let me get this straight, you don't think this is a SCONJ/acl, but would rather it be advcl? with CC/CCONJ?
Wouldn't this violate the tendency to do acl/relcl for nominals?
To be frank, this issue re-emerged exactly because of any supposed implicit uses of Vav, with the Arabic counterpart in mind - where it seems in some cases the Waw is not a coinjoiner, but possibly tagged as PART for other functions.
Thank you

**Comment by IsraelLand** [comment]
I'll just quickly add that this vav, to me, seems to function in much the same way to a relative clause, in the sentence - 
מן הראוי להותיר על כנה את הפרשנות הנוהגת בהלכה הפסוקה, ולפיה אי מתן אזהרה כדין בדבר זכות ההיוועצות בעורך-דין, אינה פוסלת כשלעצמה
its aim is to "salvage" the original referent הפרשנות in the clause insofar it avoids the need to repeat it - 
מן הראוי להותיר על כנה את הפרשנות הנוהגת בהלכה הפסוקה, [לפי הפרשנות] אי מתן אזהרה

TBH "הפרשנות הנוהגת שאי מתן אזהרה" works perfectly, but "הפרשנות הנוהגת ואי מתן אזהרה" doesn't anymore.

**Comment by amir-zeldes** [comment]
> Regarding 2, let me get this straight, you don't think this is a SCONJ/acl, but would rather it be advcl

Oh, no, whoops, for "מבנים ובהם בור מים" it should definitely be acl. I was just thinking more generally about hal-like clauses, which are often advcl. I wouldn't tag the vav as PART - either CCONJ (based on morphological/dictionary category) or SCONJ (more based on its use to introduce a clause here). It's not totally interchangeable with other SCONJ, as also in the relative-like examples you gave, so it's really a judgment call - it's between CCONJ and SCONJ, so it's a question of 'which would you rather', fewer tags possible for vav and let the tree disambiguate, or more tags and corresponding better to the tree, but maybe surprising for users and harder work for taggers.

**Comment by IsraelLand** [comment]
Right. So you think an acl+CCONJ is possible, even when the vav is in isolation (so to have fewer tags but still account for this structure by acl'ing)? Or better do a one-to-one, acl inherently entailing SCONJ?

**Comment by amir-zeldes** [comment]
Both are possible. I would guess if we put it to the UD Core Group they would probably say to go with SCONJ if we intend to use deprel `mark`, in order to match the dependency to the POS. But I don't feel passionately about it.

**Comment by IsraelLand** [comment]
Right. Thanks!
